name: Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  # Job 1: Run tests
  test:
    if: github.repository == 'HabtamuFeyera/langgraph-agent-ui'  # Only runs on the specified repository
    uses: ./.github/workflows/test.yml  # Reference to a separate test workflow

  # Job 2: Build Docker image and push to Docker Hub
  build:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu runner
    needs: [test]  # This job will run only if the test job is successful

    steps:
      - uses: actions/checkout@v4  # Checkout the latest code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Enable Docker Buildx for multi-platform builds

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Login to Docker Hub
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}  # Use the Docker username secret
          password: ${{ secrets.DOCKER_TOKEN }}    # Use the Docker token secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v3  # Build and push Docker image
        with:
          context: .  # Build from the root of the repository
          push: true  # Push the image to Docker Hub
          tags: index.docker.io/${{ secrets.DOCKER_USERNAME }}/agent-service-toolkit.service:${{ github.sha }}  # Tag with commit SHA
          file: docker/Dockerfile.service  # Path to your Dockerfile

  # Job 3: Deploy to Azure Web App
  deploy:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu runner
    needs: build  # This job will run only if the build job is successful

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2  # Azure deployment action
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}  # Azure Web App name from secrets
          slot-name: 'production'  # Deploy to the 'production' slot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Azure publish profile from secrets
          images: 'index.docker.io/${{ secrets.DOCKER_USERNAME }}/agent-service-toolkit.service:${{ github.sha }}'  # Docker image to deploy
