name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    if: github.repository == 'HabtamuFeyera/langgraph-agent-ui'
    uses: ./.github/workflows/test.yml

  build:
    runs-on: ubuntu-latest
    needs: test  # Ensure that the build job depends on the successful completion of the test job
    
    steps:
      - uses: actions/checkout@v4  # Checkout the repository's code
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Set up Buildx for multi-platform builds

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Log in to Docker Hub
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}  # Use Docker Hub username secret
          password: ${{ secrets.DOCKER_TOKEN }}    # Use Docker Hub token secret

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v3  # Build and push the Docker image
        with:
          context: .  # Use the current repository directory as the build context
          push: true  # Push the image to Docker Hub
          tags: index.docker.io/${{ secrets.DOCKER_USERNAME }}/agent-service-toolkit.service:${{ github.sha }}  # Tag image with the commit hash
          file: docker/Dockerfile.service  # Specify the Dockerfile to use for the build
